"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { ArrowLeft, RefreshCw, Settings2, MapPin, Thermometer, Droplets, CloudRain, Snowflake, Wind, Gauge, Eye, Sun, Moon, Sunrise, Sunset, CloudSun, Activity, Cloud, Navigation } from "lucide-react";
import { useMasterTheme } from "@/components/theme/MasterThemeProvider";
import { AppHeader } from "@/components/layout/AppHeader";
import { GlobalHeaderActions } from "@/components/layout/GlobalHeaderActions";

type TemperatureUnit = "C" | "F";
type WindUnit = "km/h" | "mph" | "m/s" | "knots";
type PrecipitationUnit = "mm" | "in";
type PressureUnit = "hPa" | "mb" | "inHg";
type VisibilityUnit = "km" | "mi";
type SnowDepthUnit = "cm" | "in";

type LocationData = { id?: number; name: string; latitude: number; longitude: number; country?: string; country_code?: string; timezone?: string };
type WeatherData = { temperature:number; apparentTemperature:number; humidity:number; dewPoint:number; precipitation:number; rainfall:number; snowfall:number; snowDepth:number; precipitationProbability:number; weatherCode:number; windSpeed:number; windDirection:number; windGusts:number; pressure:number; visibility:number; cloudCover:number; isDay:boolean; sunrise:string; sunset:string; high:number; low:number; uvIndex:number; moonrise:string; moonset:string; moonPhase:number; timezone:string; utcOffsetSeconds:number };
type AirQualityData = { usAqi:number; pm25:number; pm10:number; ozone:number; nitrogenDioxide:number; carbonMonoxide:number; sulphurDioxide:number };

const DEFAULT_LOCATION: LocationData = { name:"Karachi", latitude:24.8607, longitude:67.0011, country:"Pakistan", country_code:"PK", timezone:"Asia/Karachi" };

function convertTemperature(v:number,u:TemperatureUnit){return u==="F"?(v*9)/5+32:v}
function convertWindSpeed(v:number,u:WindUnit){if(u==="mph")return v*.621371;if(u==="m/s")return v/3.6;if(u==="knots")return v*.539957;return v}
function convertPrecipitation(v:number,u:PrecipitationUnit){return u==="in"?v/25.4:v}
function convertPressure(v:number,u:PressureUnit){return u==="inHg"?v*.0295299831:v}
function convertVisibility(v:number,u:VisibilityUnit){return u==="mi"?v/1609.344:v/1000}
function convertSnowDepth(v:number,u:SnowDepthUnit){return u==="in"?v/2.54:v}
function formatMetric(v:number,d=1){if(!Number.isFinite(v))return "—";return new Intl.NumberFormat("en-US",{minimumFractionDigits:d,maximumFractionDigits:d}).format(v)}
function formatTime(v:string,h24=false){if(!v)return "—";const p=v.includes("T")?v.split("T")[1]:v;const m=p.match(/^(\d{1,2}):(\d{2})/);if(!m)return v;const h=Number(m[1]),min=Number(m[2]);if(h24)return `${String(h).padStart(2,"0")}:${String(min).padStart(2,"0")}`;return `${h%12||12}:${String(min).padStart(2,"0")} ${h>=12?"PM":"AM"}`}
function getWeatherInfo(code:number){if(code===0)return{label:"Clear sky",type:"clear"};if([1,2,3].includes(code))return{label:code===3?"Overcast":"Partly cloudy",type:"cloudy"};if([51,53,55,56,57].includes(code))return{label:"Drizzle",type:"rain"};if([61,63,65,66,67,80,81,82].includes(code))return{label:"Rain",type:"rain"};if([71,73,75,77,85,86].includes(code))return{label:"Snow",type:"snow"};if([95,96,99].includes(code))return{label:"Thunderstorm",type:"storm"};return{label:"Cloudy",type:"cloudy"}}
function WeatherIcon({code,size=64}:{code:number;size?:number}){const i=getWeatherInfo(code);if(i.type==="rain")return <CloudRain size={size}/>;if(i.type==="snow")return <Snowflake size={size}/>;if(i.type==="storm")return <CloudRain size={size}/>;if(i.type==="clear")return <Sun size={size}/>;return <CloudSun size={size}/>}
function getWindDirection(d:number){return ["N","NE","E","SE","S","SW","W","NW"][Math.round(d/45)%8]}
function getAqiLabel(a:number){if(a<=50)return"Good";if(a<=100)return"Moderate";if(a<=150)return"Unhealthy for sensitive groups";if(a<=200)return"Unhealthy";if(a<=300)return"Very unhealthy";return"Hazardous"}
function getMoonPhaseLabel(p:number){if(p<.03||p>=.97)return"New Moon";if(p<.22)return"Waxing Crescent";if(p<.28)return"First Quarter";if(p<.47)return"Waxing Gibbous";if(p<.53)return"Full Moon";if(p<.72)return"Waning Gibbous";if(p<.78)return"Last Quarter";return"Waning Crescent"}
function getDayDuration(a:string,b:string){const f=(v:string)=>{const m=v.match(/T?(\d{1,2}):(\d{2})/);return m?Number(m[1])*60+Number(m[2]):null};const x=f(a),y=f(b);if(x===null||y===null)return"—";let n=y-x;if(n<0)n+=1440;return`${Math.floor(n/60)}h ${n%60}m`}
function getSunPhase(w:WeatherData,now:Date){const t=new Intl.DateTimeFormat("en-US",{timeZone:w.timezone||"UTC",hour:"2-digit",minute:"2-digit",hour12:false}).format(now);const [h,m]=t.split(":").map(Number),cur=h*60+m;const f=(v:string)=>{const x=v.match(/T?(\d{1,2}):(\d{2})/);return x?Number(x[1])*60+Number(x[2]):null};const sr=f(w.sunrise),ss=f(w.sunset);if(sr===null||ss===null)return w.isDay?"Daylight":"Night";if(cur<sr-30)return"Night";if(cur<sr)return"Dawn";if(cur<sr+45)return"Sunrise";if(cur<ss-60)return"Daylight";if(cur<ss)return"Golden hour";if(cur<ss+45)return"Dusk";if(cur<ss+90)return"Twilight";return"Night"}

function DetailCard({title,icon,children,darkMode}:{title:string;icon:React.ReactNode;children:React.ReactNode;darkMode:boolean}){return <section className={`rounded-[28px] border p-5 shadow-2xl backdrop-blur-2xl sm:p-6 ${darkMode?"border-white/10 bg-black/[.30] text-white":"border-black/10 bg-white/[.58] text-black"}`}><div className="mb-5 flex items-center gap-3"><div className={`flex h-10 w-10 items-center justify-center rounded-xl border ${darkMode?"border-white/10 bg-white/10":"border-black/10 bg-black/5"}`}>{icon}</div><h2 className="text-base font-semibold">{title}</h2></div>{children}</section>}
function MetricRow({label,value,icon,muted,darkMode}:{label:string;value:string;icon?:React.ReactNode;muted:string;darkMode:boolean}){return <div className={`flex items-center justify-between gap-4 border-b py-3.5 last:border-b-0 ${darkMode?"border-white/10":"border-black/10"}`}><div className="flex min-w-0 items-center gap-3">{icon&&<span className="shrink-0 opacity-70">{icon}</span>}<span className={`truncate text-sm ${muted}`}>{label}</span></div><span className="shrink-0 text-right text-sm font-semibold tabular-nums">{value}</span></div>}

export default function WeatherDetailsPage(){
 const router=useRouter(); const { darkMode, glass, glassSoft, muted } = useMasterTheme(); const [weather,setWeather]=useState<WeatherData|null>(null); const [airQuality,setAirQuality]=useState<AirQualityData|null>(null); const [location,setLocation]=useState<LocationData>(DEFAULT_LOCATION); const [loading,setLoading]=useState(true); const [refreshing,setRefreshing]=useState(false); const [error,setError]=useState(""); const [now,setNow]=useState(()=>new Date());
 const [temperatureUnit,setTemperatureUnit]=useState<TemperatureUnit>("C"); const [windUnit,setWindUnit]=useState<WindUnit>("km/h"); const [precipitationUnit,setPrecipitationUnit]=useState<PrecipitationUnit>("mm"); const [pressureUnit,setPressureUnit]=useState<PressureUnit>("hPa"); const [visibilityUnit,setVisibilityUnit]=useState<VisibilityUnit>("km"); const [snowDepthUnit,setSnowDepthUnit]=useState<SnowDepthUnit>("cm"); const [time24Hour,setTime24Hour]=useState(false);
 useEffect(()=>{try{const l=localStorage.getItem("smart-home-weather-location");if(l){const p=JSON.parse(l);if(p?.latitude&&p?.longitude&&p?.name)setLocation(p)}const t=localStorage.getItem("smart-home-temperature-unit");const w=localStorage.getItem("smart-home-wind-unit");const p=localStorage.getItem("smart-home-precipitation-unit");const pr=localStorage.getItem("smart-home-pressure-unit");const vi=localStorage.getItem("smart-home-visibility-unit");const s=localStorage.getItem("smart-home-snow-depth-unit");const c=localStorage.getItem("smart-home-clock-24h");if(t==="C"||t==="F")setTemperatureUnit(t);if(["km/h","mph","m/s","knots"].includes(w??""))setWindUnit(w as WindUnit);if(p==="mm"||p==="in")setPrecipitationUnit(p);if(["hPa","mb","inHg"].includes(pr??""))setPressureUnit(pr as PressureUnit);if(vi==="km"||vi==="mi")setVisibilityUnit(vi);if(s==="cm"||s==="in")setSnowDepthUnit(s);if(c==="true")setTime24Hour(true)}catch{}const i=window.setInterval(()=>setNow(new Date()),1000);return()=>window.clearInterval(i)},[]);
 async function loadWeather(show=false){try{if(show)setRefreshing(true);setError("");const q=new URLSearchParams({latitude:String(location.latitude),longitude:String(location.longitude),current:["temperature_2m","relative_humidity_2m","dew_point_2m","apparent_temperature","precipitation","rain","snowfall","snow_depth","weather_code","cloud_cover","pressure_msl","visibility","wind_speed_10m","wind_direction_10m","wind_gusts_10m","is_day"].join(","),daily:["temperature_2m_max","temperature_2m_min","precipitation_probability_max","sunrise","sunset","uv_index_max","moonrise","moonset","moon_phase"].join(","),forecast_days:"1",timezone:"auto"});const aq=new URLSearchParams({latitude:String(location.latitude),longitude:String(location.longitude),current:["us_aqi","pm2_5","pm10","ozone","nitrogen_dioxide","carbon_monoxide","sulphur_dioxide"].join(","),timezone:"auto"});const[r,ar]=await Promise.all([fetch(`https://api.open-meteo.com/v1/forecast?${q}`),fetch(`https://air-quality-api.open-meteo.com/v1/air-quality?${aq}`)]);if(!r.ok)throw new Error("Weather request failed");const d=await r.json(),ad=ar.ok?await ar.json():null,c=d.current??{},dy=d.daily??{},ac=ad?.current??{};setWeather({temperature:Number(c.temperature_2m??0),apparentTemperature:Number(c.apparent_temperature??0),humidity:Number(c.relative_humidity_2m??0),dewPoint:Number(c.dew_point_2m??0),precipitation:Number(c.precipitation??0),rainfall:Number(c.rain??0),snowfall:Number(c.snowfall??0),snowDepth:Number(c.snow_depth??0),precipitationProbability:Number(dy.precipitation_probability_max?.[0]??0),weatherCode:Number(c.weather_code??0),windSpeed:Number(c.wind_speed_10m??0),windDirection:Number(c.wind_direction_10m??0),windGusts:Number(c.wind_gusts_10m??0),pressure:Number(c.pressure_msl??0),visibility:Number(c.visibility??0),cloudCover:Number(c.cloud_cover??0),isDay:Number(c.is_day??0)===1,sunrise:dy.sunrise?.[0]??"",sunset:dy.sunset?.[0]??"",high:Number(dy.temperature_2m_max?.[0]??0),low:Number(dy.temperature_2m_min?.[0]??0),uvIndex:Number(dy.uv_index_max?.[0]??0),moonrise:dy.moonrise?.[0]??"",moonset:dy.moonset?.[0]??"",moonPhase:Number(dy.moon_phase?.[0]??0),timezone:d.timezone??location.timezone??"UTC",utcOffsetSeconds:Number(d.utc_offset_seconds??0)});setAirQuality(ad?{usAqi:Number(ac.us_aqi??0),pm25:Number(ac.pm2_5??0),pm10:Number(ac.pm10??0),ozone:Number(ac.ozone??0),nitrogenDioxide:Number(ac.nitrogen_dioxide??0),carbonMonoxide:Number(ac.carbon_monoxide??0),sulphurDioxide:Number(ac.sulphur_dioxide??0)}:null)}catch(e){console.error(e);setError("Could not load weather details.")}finally{setLoading(false);setRefreshing(false)}}
 useEffect(()=>{loadWeather();const i=window.setInterval(()=>loadWeather(),600000);return()=>window.clearInterval(i)},[location.latitude,location.longitude]);

 if(loading)return <main className={`min-h-screen p-5 ${darkMode?"text-white":"text-black"}`}><div className="mx-auto max-w-6xl space-y-5"><div className="h-16 animate-pulse rounded-[26px] bg-white/10"/><div className="h-64 animate-pulse rounded-[30px] bg-white/10"/><div className="grid gap-5 md:grid-cols-2">{[1,2,3,4,5,6].map(x=><div key={x} className="h-64 animate-pulse rounded-[28px] bg-white/10"/>)}</div></div></main>;
 if(!weather)return <main className={`min-h-screen p-5 ${darkMode?"text-white":"text-black"}`}><div className={`mx-auto max-w-3xl rounded-[30px] border p-8 text-center shadow-2xl backdrop-blur-2xl ${glass}`}><Cloud size={42} className="mx-auto opacity-50"/><h1 className="mt-4 text-2xl font-semibold">Weather unavailable</h1><p className={`mt-2 text-sm ${muted}`}>{error||"Please try again."}</p><button onClick={()=>loadWeather(true)} className={`mt-6 rounded-2xl border px-5 py-3 text-sm font-semibold ${glassSoft}`}>Try again</button></div></main>;
 const wi=getWeatherInfo(weather.weatherCode),T=convertTemperature(weather.temperature,temperatureUnit),FL=convertTemperature(weather.apparentTemperature,temperatureUnit),HI=convertTemperature(weather.high,temperatureUnit),LO=convertTemperature(weather.low,temperatureUnit),DP=convertTemperature(weather.dewPoint,temperatureUnit),WS=convertWindSpeed(weather.windSpeed,windUnit),WG=convertWindSpeed(weather.windGusts,windUnit),RF=convertPrecipitation(weather.rainfall,precipitationUnit),SF=convertPrecipitation(weather.snowfall,precipitationUnit),PR=convertPrecipitation(weather.precipitation,precipitationUnit),SD=convertSnowDepth(weather.snowDepth,snowDepthUnit),P=convertPressure(weather.pressure,pressureUnit),V=convertVisibility(weather.visibility,visibilityUnit),wu=windUnit==="knots"?"kt":windUnit, rate=precipitationUnit==="in"?"in/h":"mm/h",dir=getWindDirection(weather.windDirection),loc=`${location.name}${location.country?`, ${location.country}`:""}`,sunPhase=getSunPhase(weather,now),moonPhase=getMoonPhaseLabel(weather.moonPhase),aqiLabel=airQuality?getAqiLabel(airQuality.usAqi):"—";
 const clock=new Intl.DateTimeFormat("en-US",{hour:"2-digit",minute:"2-digit",second:"2-digit",hour12:!time24Hour,timeZone:weather.timezone||"UTC"}).format(now);
 return <main className={`relative min-h-screen overflow-hidden ${darkMode?"text-white":"text-black"}`}>
 <div className="relative z-10 mx-auto min-h-screen max-w-6xl px-4 py-5 sm:px-6"><AppHeader eyebrow="Weather" title="Weather Details" subtitle={location.name} icon={<CloudSun size={22}/>} backHref="/dashboard" backLabel="Dashboard" actions={<GlobalHeaderActions><button onClick={()=>router.push("/dashboard")} title="Weather settings" className={`flex h-10 w-10 items-center justify-center rounded-xl border ${glassSoft}`}><Settings2 size={17}/></button><button onClick={()=>loadWeather(true)} disabled={refreshing} title="Refresh weather" className={`flex h-10 w-10 items-center justify-center rounded-xl border disabled:opacity-50 ${glassSoft}`}><RefreshCw size={17} className={refreshing?"animate-spin":""}/></button></GlobalHeaderActions>} />
 {error&&<div className="mb-5 rounded-2xl border border-red-500/20 bg-red-500/10 px-4 py-3 text-sm">{error}</div>}
 <section className={`relative mb-5 overflow-hidden rounded-[34px] border p-6 shadow-2xl backdrop-blur-2xl sm:p-8 ${glass}`}><div className="absolute -right-16 -top-16 opacity-10"><WeatherIcon code={weather.weatherCode} size={260}/></div><div className="relative flex flex-col justify-between gap-8 md:flex-row md:items-center"><div><div className="flex flex-wrap items-center gap-2"><span className={`rounded-full border px-3 py-1 text-[10px] font-semibold uppercase tracking-[.18em] ${glassSoft}`}>Weather details</span><span className={`text-[10px] ${muted}`}>Live · {clock}</span></div><div className="mt-6 flex items-center gap-5"><div className={`flex h-24 w-24 items-center justify-center rounded-[28px] border ${glassSoft} ${wi.type==="clear"?(weather.isDay?"text-amber-300":"text-indigo-200"):"text-sky-200"}`}><WeatherIcon code={weather.weatherCode} size={58}/></div><div><div className="text-6xl font-semibold tracking-tight sm:text-7xl">{Math.round(T)}°{temperatureUnit}</div><p className="mt-2 text-base font-medium">{wi.label}</p><div className={`mt-2 flex items-center gap-1 text-sm ${muted}`}><MapPin size={14}/>{loc}</div></div></div></div><div className={`grid min-w-[260px] grid-cols-2 gap-3 rounded-[24px] border p-4 ${glassSoft}`}><div><p className={`text-[10px] uppercase tracking-wider ${muted}`}>Feels Like</p><p className="mt-1 text-xl font-semibold">{formatMetric(FL,1)}°{temperatureUnit}</p></div><div><p className={`text-[10px] uppercase tracking-wider ${muted}`}>High</p><p className="mt-1 text-xl font-semibold">{formatMetric(HI,1)}°{temperatureUnit}</p></div><div><p className={`text-[10px] uppercase tracking-wider ${muted}`}>Low</p><p className="mt-1 text-xl font-semibold">{formatMetric(LO,1)}°{temperatureUnit}</p></div><div><p className={`text-[10px] uppercase tracking-wider ${muted}`}>Daylight</p><p className="mt-1 text-xl font-semibold">{getDayDuration(weather.sunrise,weather.sunset)}</p></div></div></div></section>
 <div className="grid gap-5 md:grid-cols-2">
 <DetailCard title="Core Temperatures" icon={<Thermometer size={19}/>} darkMode={darkMode}><MetricRow label="Current Temperature" value={`${formatMetric(T,1)}°${temperatureUnit}`} icon={<Thermometer size={16}/>} muted={muted} darkMode={darkMode}/><MetricRow label="Feels Like" value={`${formatMetric(FL,1)}°${temperatureUnit}`} icon={<Activity size={16}/>} muted={muted} darkMode={darkMode}/><MetricRow label="High / Low" value={`${formatMetric(HI,1)}° / ${formatMetric(LO,1)}° ${temperatureUnit}`} icon={<CloudSun size={16}/>} muted={muted} darkMode={darkMode}/><MetricRow label="Dew Point" value={`${formatMetric(DP,1)}°${temperatureUnit}`} icon={<Droplets size={16}/>} muted={muted} darkMode={darkMode}/></DetailCard>
 <DetailCard title="Precipitation & Moisture" icon={<Droplets size={19}/>} darkMode={darkMode}><MetricRow label="Rainfall Amount" value={`${formatMetric(RF,2)} ${precipitationUnit}`} icon={<CloudRain size={16}/>} muted={muted} darkMode={darkMode}/><MetricRow label="Snowfall Depth" value={`${formatMetric(SD,2)} ${snowDepthUnit}`} icon={<Snowflake size={16}/>} muted={muted} darkMode={darkMode}/><MetricRow label="Precipitation Rate" value={`${formatMetric(PR,2)} ${rate}`} icon={<CloudRain size={16}/>} muted={muted} darkMode={darkMode}/><MetricRow label="Relative Humidity" value={`${Math.round(weather.humidity)}%`} icon={<Droplets size={16}/>} muted={muted} darkMode={darkMode}/><MetricRow label="Chance of Rain / Snow" value={`${Math.round(weather.precipitationProbability)}%`} icon={<CloudRain size={16}/>} muted={muted} darkMode={darkMode}/><div className={`mt-2 text-[10px] ${muted}`}>Snowfall: {formatMetric(SF,2)} {precipitationUnit}</div></DetailCard>
 <DetailCard title="Wind & Atmosphere" icon={<Wind size={19}/>} darkMode={darkMode}><MetricRow label="Wind Speed" value={`${formatMetric(WS,1)} ${wu}`} icon={<Wind size={16}/>} muted={muted} darkMode={darkMode}/><MetricRow label="Wind Gusts" value={`${formatMetric(WG,1)} ${wu}`} icon={<Wind size={16}/>} muted={muted} darkMode={darkMode}/><MetricRow label="Wind Direction" value={`${Math.round(weather.windDirection)}° ${dir}`} icon={<Navigation size={16}/>} muted={muted} darkMode={darkMode}/><MetricRow label="Atmospheric Pressure" value={`${formatMetric(P,1)} ${pressureUnit}`} icon={<Gauge size={16}/>} muted={muted} darkMode={darkMode}/></DetailCard>
 <DetailCard title="Visibility & Sky" icon={<Eye size={19}/>} darkMode={darkMode}><MetricRow label="Visibility Distance" value={`${formatMetric(V,1)} ${visibilityUnit}`} icon={<Eye size={16}/>} muted={muted} darkMode={darkMode}/><MetricRow label="Cloud Cover" value={`${Math.round(weather.cloudCover)}%`} icon={<Cloud size={16}/>} muted={muted} darkMode={darkMode}/><MetricRow label="UV Index" value={formatMetric(weather.uvIndex,1)} icon={<Sun size={16}/>} muted={muted} darkMode={darkMode}/></DetailCard>
 <DetailCard title="Air Quality Index" icon={<Activity size={19}/>} darkMode={darkMode}><MetricRow label="US AQI" value={airQuality?`${Math.round(airQuality.usAqi)} · ${aqiLabel}`:"—"} icon={<Activity size={16}/>} muted={muted} darkMode={darkMode}/><MetricRow label="PM2.5" value={airQuality?`${formatMetric(airQuality.pm25,1)} µg/m³`:"—"} muted={muted} darkMode={darkMode}/><MetricRow label="PM10" value={airQuality?`${formatMetric(airQuality.pm10,1)} µg/m³`:"—"} muted={muted} darkMode={darkMode}/><MetricRow label="O₃" value={airQuality?`${formatMetric(airQuality.ozone,1)} ppb`:"—"} muted={muted} darkMode={darkMode}/><MetricRow label="NO₂" value={airQuality?`${formatMetric(airQuality.nitrogenDioxide,1)} ppb`:"—"} muted={muted} darkMode={darkMode}/><MetricRow label="CO" value={airQuality?`${formatMetric(airQuality.carbonMonoxide,2)} ppm`:"—"} muted={muted} darkMode={darkMode}/><MetricRow label="SO₂" value={airQuality?`${formatMetric(airQuality.sulphurDioxide,1)} ppb`:"—"} muted={muted} darkMode={darkMode}/></DetailCard>
 <DetailCard title="Astronomical Times" icon={<Moon size={19}/>} darkMode={darkMode}><MetricRow label="Current Sun Phase" value={sunPhase} icon={sunPhase==="Night"?<Moon size={16}/>:<Sun size={16}/>} muted={muted} darkMode={darkMode}/><MetricRow label="Current Moon Phase" value={moonPhase} icon={<Moon size={16}/>} muted={muted} darkMode={darkMode}/><MetricRow label="Sunrise" value={formatTime(weather.sunrise,time24Hour)} icon={<Sunrise size={16}/>} muted={muted} darkMode={darkMode}/><MetricRow label="Moonrise" value={formatTime(weather.moonrise,time24Hour)} icon={<Moon size={16}/>} muted={muted} darkMode={darkMode}/><MetricRow label="Sunset" value={formatTime(weather.sunset,time24Hour)} icon={<Sunset size={16}/>} muted={muted} darkMode={darkMode}/><MetricRow label="Moonset" value={formatTime(weather.moonset,time24Hour)} icon={<Moon size={16}/>} muted={muted} darkMode={darkMode}/></DetailCard>
 </div><footer className={`mt-5 rounded-[24px] border p-4 text-center text-xs ${glass} ${muted}`}>{loc} · {weather.timezone} · Updated automatically every 10 minutes</footer></div><style jsx global>{`@keyframes rainFall{0%{transform:translateY(-30px) rotate(15deg)}100%{transform:translateY(115vh) rotate(15deg)}}`}</style></main>
}
