$ErrorActionPreference = "Stop"

# ============================================================
# PHANTOM FACTORY SECRET HEADER GENERATOR
# ============================================================

$envFile = ".\.env.local"

$sharedDir = ".\firmware\shared"
$birthDir  = ".\firmware\esp8266-birth-firmware"

$sharedOutput = Join-Path $sharedDir "FactorySecrets.generated.h"
$birthOutput  = Join-Path $birthDir  "FactorySecrets.generated.h"


# ------------------------------------------------------------
# Validate .env.local
# ------------------------------------------------------------

if (!(Test-Path $envFile)) {
    throw ".env.local not found"
}


# ------------------------------------------------------------
# Read factory key
# ------------------------------------------------------------

$line = Get-Content $envFile |
    Where-Object {
        $_ -match '^PHANTOM_FACTORY_HMAC_KEY='
    } |
    Select-Object -First 1

if (!$line) {
    throw "PHANTOM_FACTORY_HMAC_KEY missing from .env.local"
}

$key = ($line -split '=', 2)[1].Trim().Trim('"').Trim("'")


# ------------------------------------------------------------
# Validate key
# ------------------------------------------------------------

if ($key.Length -lt 32) {
    throw "Factory key is too short. Minimum 32 characters required."
}


# ------------------------------------------------------------
# Ensure directories exist
# ------------------------------------------------------------

New-Item `
    -ItemType Directory `
    -Force `
    -Path $sharedDir |
    Out-Null

New-Item `
    -ItemType Directory `
    -Force `
    -Path $birthDir |
    Out-Null


# ------------------------------------------------------------
# Generate header
# ------------------------------------------------------------

$content = @"
#pragma once

// ============================================================
// AUTO-GENERATED FACTORY SECRET
// ============================================================
// DO NOT COMMIT.
// DO NOT EDIT MANUALLY.
// Generated by:
// scripts/generate-factory-key-header.ps1
// ============================================================

#define PHANTOM_FACTORY_HMAC_KEY "$key"
"@


# ------------------------------------------------------------
# Write shared copy
# ------------------------------------------------------------

Set-Content `
    -Path $sharedOutput `
    -Value $content `
    -Encoding UTF8


# ------------------------------------------------------------
# Write Arduino sketch-local copy
# Required because Arduino IDE builds sketch from temp directory
# ------------------------------------------------------------

Set-Content `
    -Path $birthOutput `
    -Value $content `
    -Encoding UTF8


Write-Host ""
Write-Host "Factory secret headers generated successfully."
Write-Host ""
Write-Host "Shared:"
Write-Host "  $sharedOutput"
Write-Host ""
Write-Host "Birth firmware:"
Write-Host "  $birthOutput"
Write-Host ""
Write-Host "IMPORTANT: Generated headers must never be committed to Git."